### ISSUE TITLE
第381行的问题

### ISSUE THREAD

**Issue by laoshiren2** [UnblockNeteaseMusic/install-scripts#15]
[INFO] 正在启动 UnblockNeteaseMusic 服务端。。。
systemctl：无法识别的选项“--value”
install.sh: 第 381 行:[: : 期待整数表达式
[ERROR] 无法启动 UnblockNeteaseMusic 服务端。

手动执行了该命令
systemctl show --property MainPID --value
systemctl：无法识别的选项“--value”

**Comment by 1715173329** [comment]
你的 systemctl 版本过低，需要升级。

**Comment by villainousx** [comment]
systemctl：无法识别的选项“--value”
/usr/local/bin/unm-server: 第 371 行:[: : 期待整数表达式
[ERROR] 无法停止 UnblockNeteaseMusic 服务端。
@1715173329 
请教下这个也是吗

**Comment by 1715173329** [comment]
是

**Comment by nacltox** [comment]
> 是

之前解决了，现在在另一个上装又提示同样的问题，找了一圈下来还是不知道怎么升级，可以指导一下吗，感谢
