### ISSUE TITLE
无法启动服务

### ISSUE THREAD

**Issue by hugxu0** [UnblockNeteaseMusic/install-scripts#18]
### Bug 描述

[INFO] 正在启动 UnblockNeteaseMusic 服务端。。。
systemctl：无法识别的选项“–value”
install.sh: 第 381 行:[: : 期待整数表达式
[ERROR] 无法启动 UnblockNeteaseMusic 服务端。
[INFO] 正在保存本脚本到 /usr/local/bin/unm-server。。。

### 日志内容

[INFO] 正在启动 UnblockNeteaseMusic 服务端。。。
systemctl：无法识别的选项“–value”
install.sh: 第 381 行:[: : 期待整数表达式
[ERROR] 无法启动 UnblockNeteaseMusic 服务端。
[INFO] 正在保存本脚本到 /usr/local/bin/unm-server。。。

### 网易云音乐版本号

最新

### 操作系统

CentOS7.0

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint（仅 macOS 或 iOS）。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
systemd 版本太老，不支持通过 --value 参数获取 pid。
服务能起来，但是脚本无法获取状态。
