### ISSUE TITLE
无法启动服务

### ISSUE THREAD

**Issue by freeqimmy** [UnblockNeteaseMusic/install-scripts#21]
Bug 描述
[INFO] 正在配置自动更新。。。
[INFO] 正在配置 systemd 服务。。。
Created symlink /etc/systemd/system/multi-user.target.wants/unblockneteasemusic-server.service → /etc/systemd/system/unblockneteasemusic-server.service.
[INFO] 正在启动 UnblockNeteaseMusic 服务端。。。
[ERROR] 无法启动 UnblockNeteaseMusic 服务端。
[INFO] 正在保存本脚本到 /usr/local/bin/unm-server。。。
[SUCCESS] UnblockNeteaseMusic 服务端安装完毕。
[INFO] UnblockNeteaseMusic 服务端监听地址：****:13026:13027
[INFO] UnblockNeteaseMusic 服务端自动代理文件地址：http://****:13026/proxy.pac

预期行为
No response

实际行为
No response

复现步骤
No response

日志内容
尝试使用 `systemctl start /etc/systemd/system/unblockneteasemusic-server.service` 手动启动服务
报错为：Failed to start etc-systemd-system-unblockneteasemusic\x2dserver.service.mount: Unit etc-systemd-system-unblockneteasemusic\x2dserver.service.mount not found.

网易云音乐歌曲链接
No response

网易云音乐版本号
最新

操作系统
Debian 10
其他信息
No response

问题排查
 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。

**Comment by 1715173329** [comment]
systemctl status unblockneteasemusic-server.service|cat
大概是你的网络问题

**Comment by freeqimmy** [comment]
抱歉隔了这么久才给您回复。

我刚才尝试用脚本重新启动unm，还是失败了，使用您的指令得到的反馈如下：
● unblockneteasemusic-server.service - UnblockNeteaseMusic Server (Node.js version)
   Loaded: loaded (/etc/systemd/system/unblockneteasemusic-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2023-04-20 11:30:00 CST; 7s ago
  Process: 28715 ExecStart=/usr/bin/env node /usr/local/bin/unblockneteasemusic-server/app.js -a 0.0.0.0 -p $PORTS $SOURCES $ENDPOINT $HOST $PROXY $STRICT (code=exited, status=1/FAILURE)
 Main PID: 28715 (code=exited, status=1/FAILURE)

Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 5.
Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Start request repeated too quickly.
Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: Failed to start UnblockNeteaseMusic Server (Node.js version).

服务器上还部署了v2ray服务，outbound是正常的。

**Comment by freeqimmy** [comment]
抱歉隔了这么久才给您回复。

我刚才尝试用脚本重新启动unm，还是失败了，使用您的指令得到的反馈如下：
● unblockneteasemusic-server.service - UnblockNeteaseMusic Server (Node.js version)
   Loaded: loaded (/etc/systemd/system/unblockneteasemusic-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2023-04-20 11:30:00 CST; 7s ago
  Process: 28715 ExecStart=/usr/bin/env node /usr/local/bin/unblockneteasemusic-server/app.js -a 0.0.0.0 -p $PORTS $SOURCES $ENDPOINT $HOST $PROXY $STRICT (code=exited, status=1/FAILURE)
 Main PID: 28715 (code=exited, status=1/FAILURE)

Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 5.
Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Start request repeated too quickly.
Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
Apr 20 11:30:00 GreenCloud.1669228242 systemd[1]: Failed to start UnblockNeteaseMusic Server (Node.js version).

服务器上还部署了v2ray服务，outbound是正常的。

**Comment by freeqimmy** [comment]
抱歉，我github使用不熟练，按错了，带来麻烦实在抱歉Orz

**Comment by 1715173329** [comment]
journalctl -xeu unblockneteasemusic-server.service | cat
看下日志

**Comment by freeqimmy** [comment]
root@GreenCloud:~# journalctl -xeu unblockneteasemusic-server.service | cat
-- Logs begin at Fri 2023-04-28 07:54:08 CST, end at Fri 2023-04-28 14:09:01 CST. --
Apr 28 14:08:58 GreenCloud.1669228242 systemd[1]: Started UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished successfully.
--
-- The job identifier is 25261.
Apr 28 14:08:59 GreenCloud.1669228242 env[11471]: Please check the availability of match sources.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit unblockneteasemusic-server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 1.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit unblockneteasemusic-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
-- Subject: A stop job for unit unblockneteasemusic-server.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unblockneteasemusic-server.service has finished.
--
-- The job identifier is 25325 and the job result is done.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: Started UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished successfully.
--
-- The job identifier is 25325.
Apr 28 14:08:59 GreenCloud.1669228242 env[11479]: Please check the availability of match sources.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit unblockneteasemusic-server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 2.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit unblockneteasemusic-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
-- Subject: A stop job for unit unblockneteasemusic-server.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unblockneteasemusic-server.service has finished.
--
-- The job identifier is 25389 and the job result is done.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: Started UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished successfully.
--
-- The job identifier is 25389.
Apr 28 14:09:00 GreenCloud.1669228242 env[11486]: Please check the availability of match sources.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit unblockneteasemusic-server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 3.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit unblockneteasemusic-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
-- Subject: A stop job for unit unblockneteasemusic-server.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unblockneteasemusic-server.service has finished.
--
-- The job identifier is 25453 and the job result is done.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: Started UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished successfully.
--
-- The job identifier is 25453.
Apr 28 14:09:00 GreenCloud.1669228242 env[11493]: Please check the availability of match sources.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit unblockneteasemusic-server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 4.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit unblockneteasemusic-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
-- Subject: A stop job for unit unblockneteasemusic-server.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unblockneteasemusic-server.service has finished.
--
-- The job identifier is 25517 and the job result is done.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: Started UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished successfully.
--
-- The job identifier is 25517.
Apr 28 14:09:01 GreenCloud.1669228242 env[11500]: Please check the availability of match sources.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit unblockneteasemusic-server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit unblockneteasemusic-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
-- Subject: A stop job for unit unblockneteasemusic-server.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unblockneteasemusic-server.service has finished.
--
-- The job identifier is 25581 and the job result is done.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Start request repeated too quickly.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: Failed to start UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished with a failure.
--
-- The job identifier is 25581 and the job result is failed.

**Comment by freeqimmy** [comment]
```
root@GreenCloud:~# journalctl -xeu unblockneteasemusic-server.service | cat
-- Logs begin at Fri 2023-04-28 07:54:08 CST, end at Fri 2023-04-28 14:09:01 CST. --
Apr 28 14:08:58 GreenCloud.1669228242 systemd[1]: Started UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished successfully.
--
-- The job identifier is 25261.
Apr 28 14:08:59 GreenCloud.1669228242 env[11471]: Please check the availability of match sources.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit unblockneteasemusic-server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 1.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit unblockneteasemusic-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
-- Subject: A stop job for unit unblockneteasemusic-server.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unblockneteasemusic-server.service has finished.
--
-- The job identifier is 25325 and the job result is done.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: Started UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished successfully.
--
-- The job identifier is 25325.
Apr 28 14:08:59 GreenCloud.1669228242 env[11479]: Please check the availability of match sources.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit unblockneteasemusic-server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 2.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit unblockneteasemusic-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
-- Subject: A stop job for unit unblockneteasemusic-server.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unblockneteasemusic-server.service has finished.
--
-- The job identifier is 25389 and the job result is done.
Apr 28 14:08:59 GreenCloud.1669228242 systemd[1]: Started UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished successfully.
--
-- The job identifier is 25389.
Apr 28 14:09:00 GreenCloud.1669228242 env[11486]: Please check the availability of match sources.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit unblockneteasemusic-server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 3.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit unblockneteasemusic-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
-- Subject: A stop job for unit unblockneteasemusic-server.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unblockneteasemusic-server.service has finished.
--
-- The job identifier is 25453 and the job result is done.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: Started UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished successfully.
--
-- The job identifier is 25453.
Apr 28 14:09:00 GreenCloud.1669228242 env[11493]: Please check the availability of match sources.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit unblockneteasemusic-server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 4.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit unblockneteasemusic-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
-- Subject: A stop job for unit unblockneteasemusic-server.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unblockneteasemusic-server.service has finished.
--
-- The job identifier is 25517 and the job result is done.
Apr 28 14:09:00 GreenCloud.1669228242 systemd[1]: Started UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished successfully.
--
-- The job identifier is 25517.
Apr 28 14:09:01 GreenCloud.1669228242 env[11500]: Please check the availability of match sources.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit unblockneteasemusic-server.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit unblockneteasemusic-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: Stopped UnblockNeteaseMusic Server (Node.js version).
-- Subject: A stop job for unit unblockneteasemusic-server.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unblockneteasemusic-server.service has finished.
--
-- The job identifier is 25581 and the job result is done.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Start request repeated too quickly.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: unblockneteasemusic-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unblockneteasemusic-server.service has entered the 'failed' state with result 'exit-code'.
Apr 28 14:09:01 GreenCloud.1669228242 systemd[1]: Failed to start UnblockNeteaseMusic Server (Node.js version).
-- Subject: A start job for unit unblockneteasemusic-server.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unblockneteasemusic-server.service has finished with a failure.
--
-- The job identifier is 25581 and the job result is failed.
```

**Comment by 1715173329** [comment]
`Please check the availability of match sources`
音源写错了，自己再去检查下
多个音源是用 __空格__ 隔开

https://github.com/UnblockNeteaseMusic/server#%E9%9F%B3%E6%BA%90%E6%B8%85%E5%8D%95
